const UPDATE_INCREMENT_VISITHISTORY = `
    UPDATE
        VISITHISTORY
    SET
        TOTAL = TOTAL + 1
        , TODAY = TODAY + 1
`;

const UPDATE_INITIATE_TOTAY_VISITHISTORY = `
    UPDATE
        VISITHISTORY
    SET
        TODAY = 0
`;

export { UPDATE_INCREMENT_VISITHISTORY, UPDATE_INITIATE_TOTAY_VISITHISTORY };
